### PR TITLE
Fix: Use non-Hispanic data for Black, Asian, and other race estimates

### LINKED ISSUE #145: Census variable selection?
Why are race totals assigned by the following variables

```
r_whi = "P12I_001N"
r_bla = "P12B_001N"
r_his = "P12H_001N"
r_asi = c("P12D_001N", "P12E_001N")
r_oth = c("P12C_001N", "P12F_001N", "P12G_001N")
```

which correspond to the following Census tables

2020 DHC table | 2010 DHC table | Title
-- | -- | --
P12B | P12B | SEX BY AGE FOR   SELECTED AGE CATEGORIES (BLACK OR AFRICAN AMERICAN ALONE)
P12C | P12C | SEX   BY AGE FOR SELECTED AGE CATEGORIES (AMERICAN INDIAN AND ALASKA NATIVE   ALONE)
P12D | P12D | SEX   BY AGE FOR SELECTED AGE CATEGORIES (ASIAN ALONE)
P12E | P12E | SEX   BY AGE FOR SELECTED AGE CATEGORIES (NATIVE HAWAIIAN AND OTHER PACIFIC   ISLANDER ALONE)
P12F | P12F | SEX   BY AGE FOR SELECTED AGE CATEGORIES (SOME OTHER RACE ALONE)
P12G | P12G | SEX   BY AGE FOR SELECTED AGE CATEGORIES (TWO OR MORE RACES)
P12H | P12H | SEX   BY AGE FOR SELECTED AGE CATEGORIES (HISPANIC OR LATINO)
P12I | P12I | SEX   BY AGE FOR SELECTED AGE CATEGORIES (WHITE ALONE, NOT HISPANIC OR LATINO)

and not the following tables' variables instead?

2020 DHC table | 2010 DHC table | Title
-- | -- | --
P12H | P12H | SEX BY AGE FOR   SELECTED AGE CATEGORIES (HISPANIC OR LATINO)
P12I | P12I | SEX   BY AGE FOR SELECTED AGE CATEGORIES (WHITE ALONE, NOT HISPANIC OR LATINO)
P12J | N/A | SEX   BY AGE FOR SELECTED AGE CATEGORIES (BLACK OR AFRICAN AMERICAN ALONE, NOT   HISPANIC OR LATINO)
P12K | N/A | SEX   BY AGE FOR SELECTED AGE CATEGORIES (AMERICAN INDIAN AND ALASKA NATIVE ALONE,   NOT HISPANIC OR LATINO)
P12L | N/A | SEX   BY AGE FOR SELECTED AGE CATEGORIES (ASIAN ALONE, NOT HISPANIC OR LATINO)
P12M | N/A | SEX   BY AGE FOR SELECTED AGE CATEGORIES (NATIVE HAWAIIAN AND OTHER PACIFIC   ISLANDER ALONE, NOT HISPANIC OR LATINO)
P12N | N/A | SEX   BY AGE FOR SELECTED AGE CATEGORIES (SOME OTHER RACE ALONE, NOT HISPANIC OR   LATINO)
P12O | N/A | SEX   BY AGE FOR SELECTED AGE CATEGORIES (TWO OR MORE RACES, NOT HISPANIC OR   LATINO)

Using the former yields aggregate population counts that exceed the population total for each geography because it ought to double-count non-white Hispanic or Latino individuals. The latter yields matching counts.

### PR DESCRIPTION
**Pull request by rossellhayes**
This PR updates the tables pulled by `census_geo_api()`. It will now pull non-Hispanic tables to estimate Black, Asian, and other race populations. Previously, Hispanic respondents could be double counted because they may count towards both the Hispanic population and the Black, Asian, or other race populations of a geography.

Fixes #145.

### CODE REVIEW

**Comment by kosukeimai** [comment]
@etrrosenman Please let us know if this looks good to you.  Thanks.

**Review by etrrosenman — COMMENTED** [review]
Looks good to me!

**Comment by etrrosenman** [comment]
Changes look good to me!

**Comment by 1beb** [comment]
We also did some due diligence by comparing estimates at state level to TargetSmart Voter File Race and CPS 2022 targets. They look better than previous, with the black and hispanic registered voters having more reasonable proportions. I'm going to merge this branch, then submit as a bugfix to CRAN.

**Pull request merged**
