### PR TITLE
WIP: Adding parallel processing

### PR DESCRIPTION
**Pull request by 1beb**
DO NOT MERGE: This is a work in progress.

@kosukeimai @kkprinceton Please review the description below. If the changes are welcome, I will formalize the pull request and complete the todos. 

HI All! Thank you for this wonderful package. I've made a few adjustments that could be useful to you and others: 

1. Added parallel processing `census_geo_api` to expedite the process of connecting with the API via the `get_census_api` function. The implementation is setup such that there will be a county-per-thread model. Ostensibly, a user would specify their own plan, for example: `library(future); plan(multisession)`. This has significantly decreased the total time to run the process. Currently uses `furrr::future_map_dfr` with a progress indicator. Reduces the processing time for a state from more than a day to less than an hour. 
2. Converted `print` to `message` so that it follows stdin/out convention.
3. Setting default retries to 3. This avoids issues where minor internet instability requires a process restart. 
4. Additional log messaging to identify the start of a long process. 
5. Updated description to alphabetize imports, add future, furr and purr. 
6. Updated roxygen docs.
7. Adding `wru.png` to .Rbuildignore to relagate an `R CMD check` note.

TODO: 

- [x] R CMD CHECK
- [x] Update readme with example of using plan(multisession)

### CODE REVIEW

**Comment by kosukeimai** [comment]
@1beb Thanks for your contributions!  The additions look great.

**Comment by 1beb** [comment]
Looks like a problem with gdal-config for macOS. You may need to `brew install gdal` and trigger the builds again. 

image

**Comment by solivella** [comment]
Hi @1beb! This is such a great idea! I am wondering, though, if the Census servers could construe this as a DOS attack?

**Comment by 1beb** [comment]
Running on a 32 core machine. Have not noticed failures. I expect that you would eventually get rate-limited, their stated query limit is 500 per day, but I think it's effectively much larger (because I've been hammering it for days). Obviously YMMV. 

https://www.census.gov/data/developers/guidance/api-user-guide/help.html#:~:text=Query%20Limits,register%20for%20a%20Census%20key.

**Comment by andret6** [comment]
Hey this amazing, very excited to see somebody testing this. 

This may be a totally remedial question but is this distinct from how the tidycensus package queries the census servers? I know that pack is quite fast by comparison

**Comment by 1beb** [comment]
I can't comment on tidycensus because I'm not familiar with it. There is another problem with this package that I am working on.

When you pred_race for a tract or block, it downloads census_geo_api data for all counties rather than just those counties that are in your data. I have some code that I'm working with locally that adds a use_counties flag to the pred_race function that, when true, reduces what I believe to be unneeded pulls from census_geo_api.

**Comment by 1beb** [comment]
It might be prudent to have a short web meet with the package owner to discuss as I'm not sure if I'm breaking something and also noticed that there are some "_new" functions included that I have not reviewed. @kosukeimai would that be you?

I'm open next week, you can use brandon at bertelsen dot ca to coordinate. 

Thanks!

**Comment by 1beb** [comment]
Closing this pull request and instead branching off of [whru](https://github.com/kosukeimai/wru/tree/hwru) branch as discussed.

**Pull request closed without merging**
