### PR TITLE
Revision with Kosuke's suggestion on function name and input parameter name. Also, I included the county level prediction in race.pred.

### PR DESCRIPTION
**Pull request by HJ08003**
In addition to the name changes, I also included the county level prediction in race.pred (this was added May 18, 2016 at the Master branch).

My testing scripts:
============
tbl <- read.csv("../example/FL-Oct2014-00-00-00.tsv", sep="\t",
header=TRUE, stringsAsFactors = FALSE, colClasses = "character")
tbl$age <- as.numeric(tbl$age)
tbl$sex <- ifelse(tbl$sex == "M", 0, 1)
tbl$party <- ifelse(tbl$party == "Republican", 2, tbl$party)
tbl$party <- ifelse(tbl$party == "Democratic", 1, tbl$party)
tbl$party <- ifelse((tbl$party == "1") | (tbl$party == "2"), tbl$party,
0)

# Please use the census key you have 
key = "......"

y <- getCensusData(key, state = "FL", demo = FALSE)
yyy <- getCensusData(key, state = c("DE", "NJ"), demo = FALSE)
yy <- yyy
yy[["FL"]] <- y[["FL"]]

names(y)
[1] "FL"
names(yy)
[1] "NJ" "DE" "FL"
names(yyy)
[1] "DE" "NJ"

x1 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract",
census.key = key, census.data = y, demo = FALSE)
x2 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract",
census.key = key, demo = FALSE)
x3 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract",
census.key = key, census.data = yy, demo = FALSE)
x4 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract",
census.key = key, census.data = yyy, demo = FALSE)

x1 <- race.pred(voters = tbl, name.clean = TRUE, census = "block",
census.key = key, census.data = y, demo = FALSE)
x2 <- race.pred(voters = tbl, name.clean = TRUE, census = "block",
census.key = key, demo = FALSE)
x3 <- race.pred(voters = tbl, name.clean = TRUE, census = "block",
census.key = key, census.data = yy, demo = FALSE)
x4 <- race.pred(voters = tbl, name.clean = TRUE, census = "block",
census.key = key, census.data = yyy, demo = FALSE)

x <- x1
sum(x != x2, na.rm=T)
sum(x == x2, na.rm=T)
sum(is.na(x) == is.na(x2), na.rm=T)
sum(is.na(x) != is.na(x2), na.rm=T)

sum(x != x2, na.rm=T)
[1] 0
sum(x == x2, na.rm=T)
[1] 149188
sum(is.na(x) == is.na(x2), na.rm=T)
[1] 157500
sum(is.na(x) != is.na(x2), na.rm=T)
[1] 0

Similarly, x3 and x4 are tested against x2 to make sure the results are
the same.

### CODE REVIEW

**Comment by kosukeimai** [comment]
Hubert, there is a travis error in the latest commit

**Comment by HJ08003** [comment]
Hi Kosuke and Kabir,

It is caused by "Found warnings, treating as errors (as requested).", which is related to the duplication of of notation of voters (introduced by the revision on May 18, 2016 at the master branch).

#' @param voters An object of class \code{data.frame}. Must contain a field for
#'  surname (\code{surname}). Optional fields include Census county (\code{county}),
#'  tract (\code{tract}), block (\code{block}), party registration (\code{party}),
#'  age (\code{age}), and sex (\code{sex}).
#'
#' @param voters An object of class \code{data.frame}. Must contain field(s)
#'  named \code{\var{county}}, \code{\var{tract}}, and/or \code{\var{block}}
#'  specifying geolocation. These should be character variables that match up with
#'  U.S. Census categories. County should be three characters (e.g., "031" not "31"),
#'  tract should be six characters, and block should be four characters.

The first paragraph was modified in that revision, and the second paragraph was added there. Maybe Kabir could give me suggestion on which one to keep.

Thanks,

-Hubert

**Comment by kkprinceton** [comment]
I went through Hubert's code, and it looks okay. The second paragraph below is more up to date, but we should revise it to include the 'state' field. I'll update the documentation before we submit to CRAN.

Hubert, can I give you a call tomorrow to discuss?

________________________________

**Comment by HJ08003** [comment]
I removed the first voters paragraph. I also updated the voters parameter description in census.helper.api.<https://github.com/HJ08003/wru/blob/master/R/census.helper.api.R>local and census.helper.api<https://github.com/HJ08003/wru/blob/master/R/census.helper.api.R>.
Thanks,

-Hubert

**Comment by HJ08003** [comment]
There is a new version

**Pull request closed without merging**
