### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by solivella**
Fix two major bugs:
- Use of `predict_race_new`, which was resulting in scrambled predictions for initial races
- Use of `[` instead of `pull()` to access column in name dictionaries, which resulted in unexpected behavior due to tibble type-safety features.

### CODE REVIEW

**Comment by 1beb** [comment]
A good convention here would be to include a test that verifies the bug is fixed. Do we have a reprex for the initial bug?

**Comment by kosukeimai** [comment]
@solivella Thoughts?

**Comment by 1beb** [comment]
@solivella @kosukeimai a group of us are actively working on this package for the next sprint. We will pick up the rest of the changes to this PR.

**Comment by kosukeimai** [comment]
Great. Thanks @1beb

**Comment by 1beb** [comment]
Closing here merging into dev #120

**Pull request closed without merging**
