### PR TITLE
Enable census information pre-download

### PR DESCRIPTION
**Pull request by HJ08003**
The old census.helper.api, which does the realtime online download census data, is renamed to census.helper.api.online. I keep this so to compare the result to make sure consistency of the code.

The new function census.helper.api.local take a pre-download census object, instead of the realtime online access.

The new census.helper.api combines the above into one. If a census object is provided, it will use it instead of realtime online downloading from the census wetsite. However, if the census object does not contain the required information for the state in the data, it will try to realtime download from the census website if a valid key is provided.

Returned by getStateCensusData(), a census object is a list, indexed by state names. For example, it could be for “FL only”, or “FL, NJ and DE”.

====== testing script =======

tbl <- read.csv("../example/FL-Oct2014-00-00-00.tsv", sep="\t", header=TRUE, stringsAsFactors = FALSE, colClasses = "character")
tbl$age <- as.numeric(tbl$age)
tbl$sex <- ifelse(tbl$sex == "M", 0, 1)
tbl$party <- ifelse(tbl$party == "Republican", 2, tbl$party)
tbl$party <- ifelse(tbl$party == "Democratic", 1, tbl$party)
tbl$party <- ifelse((tbl$party == "1") | (tbl$party == "2"), tbl$party, 0)

y <- getStateCensusData("...", state = "FL", demo = FALSE)
yyy <- getStateCensusData("...", state = c("DE", "NJ"), demo = FALSE)
yy <- yyy
yy[["FL"]] <- y[["FL"]]

> names(y)
[1] "FL"
> names(yy)
[1] "NJ" "DE" "FL"
> names(yyy)
[1] "DE" "NJ"

x1 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract", census.key = "...", censusData = y, demo = FALSE)
x2 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract", census.key = "...", demo = FALSE)
x3 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract", census.key = "...", censusData = yy, demo = FALSE)
x4 <- race.pred(voters = tbl, name.clean = TRUE, census = "tract", census.key = "...", censusData = yyy, demo = FALSE)

x1 <- race.pred(voters = tbl, name.clean = TRUE, census = "block", census.key = "...", censusData = y, demo = FALSE)
x2 <- race.pred(voters = tbl, name.clean = TRUE, census = "block", census.key = "...", demo = FALSE)
x3 <- race.pred(voters = tbl, name.clean = TRUE, census = "block", census.key = "...", censusData = yy, demo = FALSE)
x4 <- race.pred(voters = tbl, name.clean = TRUE, census = "block", census.key = "...", censusData = yyy, demo = FALSE)

x <- x1
sum(x != x2, na.rm=T)
sum(x == x2, na.rm=T)
sum(is.na(x) == is.na(x2), na.rm=T)
sum(is.na(x) != is.na(x2), na.rm=T)

> sum(x != x2, na.rm=T)
[1] 0
> sum(x == x2, na.rm=T)
[1] 149188
> sum(is.na(x) == is.na(x2), na.rm=T)
[1] 157500
> sum(is.na(x) != is.na(x2), na.rm=T)
[1] 0

Similarly, x3 and x4 are tested against x2 to make sure the results are
same.

### CODE REVIEW

**Comment by kosukeimai** [comment]
Let's change the function name from "getStateCensusData" to
"getCensusData".  Also, change the argument name from "censusData" to
"census.data"

Kosuke Imai
Professor, Department of Politics
Center for Statistics and Machine Learning
Princeton University
http://imai.princeton.edu

**Comment by HJ08003** [comment]
Sure, I will do that to be consistent with the naming convention of the rest of the code.

Thanks

Hubert

On Nov 18, 2016 6:34 PM, Kosuke Imai <notifications@github.com> wrote:
Let's change the function name from "getStateCensusData" to
"getCensusData". Also, change the argument name from "censusData" to
"census.data"

Kosuke Imai
Professor, Department of Politics
Center for Statistics and Machine Learning
Princeton University
http://imai.princeton.edu

**Comment by kosukeimai** [comment]
@kkprinceton Can you take a look at Hubert's code?

**Comment by kkprinceton** [comment]
Sure. We should probably run all the CRAN tests as well. I can also edit the help files next week.

On Nov 19, 2016, at 7:54 AM, Kosuke Imai <notifications@github.com<mailto:notifications@github.com>> wrote:


@kkprinceton<https://github.com/kkprinceton> Can you take a look at Hubert's code?

**Comment by kosukeimai** [comment]
CRAN test is done automatically now through travis ci whenever a commit is done. Better to use branching for this reason for development.

**Comment by HJ08003** [comment]
I have a new version
(1) Sync with the newest WRU code which has race.pred at county leve.
(2) getStateCensusData to getCensusData; and input argument censusData to census.data (to distinguish it from the function censusData)

**Pull request closed without merging**
