### PR TITLE
Allows census data download at levels users prefer (block, tract, cou…

### PR DESCRIPTION
**Pull request by HJ08003**
(1) Revised get_census_data function such that users can specify which level of geography to download.
(2) Updated/added examples in README.md

### CODE REVIEW

**Comment by kosukeimai** [comment]
Looks good to me.  One suggestion: when the error occurs, we should suggest that users download small chunks (in addition to trying it again).  @kkprinceton Please review the changes @HJ08003 made.  Thanks.

**Comment by HJ08003** [comment]
Downloading small chunks is not an easy solution. That requires a big change in the current code, as the census information need to be organized in a better way to allow chucks to be merged together easily and safely.

Right now, the data are stored as lists of arrays, assuming they are in some predefined order. As long as it is collected by a function as a whole package, the data integrity is guaranteed. If we let users to add smaller chucks to the census object, we need to add code to check the integrity of the census object. Even complicating, that check may require visiting the census website for the information on the relationship between county, tract and block. Besides, making census objects more complicate will also hurt the efficient of the code.

Thanks,

-Hubert

**Comment by kosukeimai** [comment]
It's a fine solution since the analysis is independently done for each geographical unit. in fact, there is no need to merge.  users just need to do the analyses separately.

**Comment by kosukeimai** [comment]
I think @HJ08003 tested it.  Is that right?  If so, let's merge the branch and then release a new version (submit it to CRAN).  Thanks.

**Pull request merged**
