### PR TITLE
Added place as a geography

### PR DESCRIPTION
**Pull request by avesh-krishna**

### CODE REVIEW

**Comment by kosukeimai** [comment]
@avesh-krishna Please make sure that your pull request passes the travis check, which is currently failing

**Comment by avesh-krishna** [comment]
It passes now.

On Mon, Jul 10, 2017 at 8:55 PM Kosuke Imai

<
mailto:Kosuke Imai <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/avesh-krishna
Please make sure that your pull request passes the travis check, which is currently failing

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/kosukeimai/wru/pull/28#issuecomment-314291533
, or

**Comment by HJ08003** [comment]
Hi Avesh,

I just tested the code, including running the this command:
    predict_race(voter.file = voters, census.geo = "place", census.key = k, party = "PID")

I got an error message for not having a column named 'county'. In fact, what the sample data doesn't have is a column named 'place'. So predict_race.R needs to be modified accordingly to provide the appropriate error message:
  if (census.geo == "place") {
    if (!("place" %in% names(voter.file))) {
      stop("voter.file object needs to have a column named county.")
    }

BTW, we need to include a column 'place' in the sample data, i.e. data/voters.RData. Could you please add that to make the package self consistent on the sample data?

Besides, we may needs to add a paragraph in README.Rd to show an example of race prediction at the 'place' level.

Thanks,

-Hubert

**Comment by kosukeimai** [comment]
@HJ08003 Instead of creating a separate example, can you create an example that looks like the other examples for tract and county?

**Comment by HJ08003** [comment]
Since this is a new feature and the current built-in sample data (voters) does not have a column named place, I added the example this way. 

Sure, I can also put the example together with other county and tract examples. But that requires multiple changes, such as making a new voter.RData and even including an example in the man page of predict_race. It is not easy to do these by editing ASCII files on the spot at Github.

How about we merge this latest version first, and I will sync the update and do these in my branch?

**Comment by kosukeimai** [comment]
I think you can check out this branch from `avesh-krishna/wru` and then commit changes there.

**Comment by HJ08003** [comment]
I already have a branch forked from your Github for wru. It seems Github is not letting me fork another branch of wru under the same account.

**Comment by HJ08003** [comment]
A pull request has been sent to avesh-krishna/wru.

**Comment by kosukeimai** [comment]
@HJ08003 Why do we have `census.key = "...",` now instead of `census.key = "",`?

**Comment by kosukeimai** [comment]
@kkprinceton Can you please review this pull request and see if everything (I noticed one thing above) looks okay.  Thanks.

**Comment by HJ08003** [comment]
“…” is what we have in the examples in those man/*.Rd files. So I changed them in README.Rd accordingly to match what’s in the man pages.
-Hubert

**Comment by kosukeimai** [comment]
What does it mean?  Does it mean users need to supply it when they use this function?

**Comment by HJ08003** [comment]
Yes, they need to provide a census key to access the census data.

**Comment by kosukeimai** [comment]
Then, let's say that explicitly in the document.

**Comment by HJ08003** [comment]
It is already mentioned in README.Rd: In order to predict race/ethnicity based on surnames AND geolocation, first request a U.S. Census API key here. Once you have an API key, you can use the package to download relevant Census geographic data on demand and condition race/ethnicity predictions on geolocation (county, tract, or block).

But it does not mentioned 'place' which is the new feature.  I will add it.

**Comment by kosukeimai** [comment]
You should say users need to put their own key into `...`

**Comment by HJ08003** [comment]
Added that in README.Rd

**Comment by kosukeimai** [comment]
To which branch?

**Comment by HJ08003** [comment]
Sorry, I accidentally added them to your branch, instead of Avesh's. 
Now I have added that to Avesh's README.Rd too.

**Comment by kosukeimai** [comment]
@kkprinceton Please check all the changes and merge them if they look okay to you.  Let's submit a new version to CRAN

**Comment by HJ08003** [comment]
Hi Kosuke, I have reverted my two commits to your Branch's README.Rd.

**Comment by kosukeimai** [comment]
@kkprinceton Why don't you make those two minor changes and submit it to CRAN?  Thanks.

**Pull request merged**
