### PR TITLE
Add tests to the package

### PR DESCRIPTION
**Pull request by HJ08003**
(1) Used devtools::use_testthat() to generate the tests directory/files.
(2) Added testthat/*.R for test cases.
(3) Verified by "R CMD check --as-cran" for both cases with a valid key provided and without.

### CODE REVIEW

**Comment by kosukeimai** [comment]
@HJ08003 I don't think you are implementing the `testthat` package correctly.  The current code just runs a bunch of commands without any testing.  Please read [this document](https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf) carefully.  You will need to use `expect_that()` and `test_that()` etc.

**Comment by HJ08003** [comment]
Both expect_that() and test_that() are used in this revision. 

I have done "R CMD check --as-cran" for the case where a valid key provided (my key). After that, I remove the valid key and retested it.

**Comment by HJ08003** [comment]
The precision I use for the tests is 4 digits after the decimal point.

**Comment by kosukeimai** [comment]
Please store in the directory `inst/tests` as recommended in this [document](https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf)  Also, can you make sure that all the options are tested in this script so that if anything breaks we can catch it?  Thanks.

**Comment by HJ08003** [comment]
I used devtools::use_testthat() to create the test directory according to the instruction in
    http://r-pkgs.had.co.nz/tests.html   (R packages by Hadley Wickham)
Also I followed some examples. They are https://github.com/SensitiveQuestions/list and https://github.com/conjugateprior/austin , where both use the same tests structure I have here. I think this is Hadley's new style.

**Comment by HJ08003** [comment]
I will add a few more cases to use at 'place' and 'block' level. However, the 'block' level test usually take much longer time than 'tract' (which is about a few minutes).

**Comment by HJ08003** [comment]
Added tests for 'place' and 'block' level prediction. With only the 8 DC/NJ voters kept in the block level prediction, the test took about 17 minutes for "R CMD check --as-cran".

**Comment by kosukeimai** [comment]
There is a limit on time for CRAN check. I think it's 5 minutes or so.  Make sure that the test does not exceed the limit.  Also, did you add checks for all options?

**Comment by HJ08003** [comment]
Since I took my census key out when I submitted the changes to Github, that version will skip the key based tests. Thus, it won't be a problem at CRAN check or travis-ci check.

R CMD check --as-cran is on local machine.

**Comment by HJ08003** [comment]
With a valid census key provided, I tested it for predictions using census informatio at county, tract, block and place. With or without a census key provided, I tested for sirname only predictions.

**Comment by HJ08003** [comment]
Among all the tests, there are TRUE and FALSE (default) for the age option. Also there are TRUE and FALSE for the sex option. Most tests are with party option to be the default, and one test used "PID". I also tested using prediction using census objects.

**Comment by HJ08003** [comment]
Added a case for testing with 2000 census data.

**Comment by kosukeimai** [comment]
@HJ08003 Can you annotate your testing code so that it's easy to understand what's been tested?

**Comment by HJ08003** [comment]
Comments added for the test cases.

**Comment by kosukeimai** [comment]
@kkprinceton Can you please review this and submit a new version to CRAN if they look okay?  Thanks.

**Pull request merged**
